src/accounts/urls.py
from django.urls import path

from .views import (
    ActivateView,
    ChangeEmailActivateView,
    ChangeEmailView,
    ChangePasswordView,
    ChangeProfileView,
    LogInView,
    LogOutView,
    RemindUsernameView,
    ResendActivationCodeView,
    RestorePasswordConfirmView,
    RestorePasswordDoneView,
    RestorePasswordView,
    SignUpView,
)

app_name = "accounts"

urlpatterns = [
    path("log-in/", LogInView.as_view(), name="log_in"),
    path("log-out/", LogOutView.as_view(), name="log_out"),
    path(
        "resend/activation-code/",
        ResendActivationCodeView.as_view(),
        name="resend_activation_code",
    ),
    path("sign-up/", SignUpView.as_view(), name="sign_up"),
    path("activate/<code>/", ActivateView.as_view(), name="activate"),
    path("restore/password/", RestorePasswordView.as_view(), name="restore_password"),
    path(
        "restore/password/done/",
        RestorePasswordDoneView.as_view(),
        name="restore_password_done",
    ),
    path(
        "restore/<uidb64>/<token>/",
        RestorePasswordConfirmView.as_view(),
        name="restore_password_confirm",
    ),
    path("remind/username/", RemindUsernameView.as_view(), name="remind_username"),
    path("change/profile/", ChangeProfileView.as_view(), name="change_profile"),
    path("change/password/", ChangePasswordView.as_view(), name="change_password"),
    path("change/email/", ChangeEmailView.as_view(), name="change_email"),
    path(
        "change/email/<code>/",
        ChangeEmailActivateView.as_view(),
        name="change_email_activation",
    ),
]

src/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView

from src import settings
from src.engine.views import ChangeLanguageView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("language/", ChangeLanguageView.as_view(), name="change_language"),
    path("accounts/", include("src.accounts.urls")),
    path("applications/", include("src.engine.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("engine:list")), name="index"),
    path("", include("django_prometheus.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/content/templates/layouts/default/page.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="SQRS project">
    <meta name="author" content="BS18">

    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title>SQRS</title>

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <a class="navbar-brand" href="/">{% trans 'Home' %}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.first_name }} {{ user.last_name }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'accounts:change_profile' %}">
                            Change profile</a>
                        <a class="dropdown-item" href="{% url 'accounts:change_email' %}">
                            Change email</a>
                        <a class="dropdown-item" href="{% url 'accounts:change_password' %}">
                            Change password</a>
                        <a class="dropdown-item" href="{% url 'accounts:log_out' %}">
                            Log Out</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <form class="form-inline ml-auto">
                <a href="{% url 'accounts:log_in' %}" class="btn btn-outline-secondary">
                    Log In</a>
                <a href="{% url 'accounts:sign_up' %}" class="btn btn-primary ml-2">
                    Sign up</a>
            </form>
            {% endif %}
        </div>
    </div>
</nav>

<div class="container-fluid mt-3">

    {% bootstrap_messages %}
    <div class="body-content">
        {% block content %}
        No content.
        {% endblock %}
    </div>
</div>

<script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>