src/engine/urls.py
from django.urls import path

from .views import (
    ApplicationCreateView,
    ApplicationDeleteView,
    ApplicationListView,
    ApplicationUpdateView,
)

app_name = "engine"

urlpatterns = [
    path("list/", ApplicationListView.as_view(), name="list"),
    path("create/", ApplicationCreateView.as_view(), name="create"),
    path("<int:pk>/delete/", ApplicationDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", ApplicationUpdateView.as_view(), name="update"),
]

src/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView

from src import settings
from src.engine.views import ChangeLanguageView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("language/", ChangeLanguageView.as_view(), name="change_language"),
    path("accounts/", include("src.accounts.urls")),
    path("applications/", include("src.engine.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("engine:list")), name="index"),
    path("", include("django_prometheus.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/engine/models.py
from django.contrib.auth.models import User
from django.db import models
from django_prometheus.models import ExportModelOperationsMixin


class Application(ExportModelOperationsMixin("application"), models.Model):  # type: ignore
    class Quarter(ExportModelOperationsMixin("quarter"), models.IntegerChoices):  # type: ignore
        Q1 = 1, "Q1"
        Q2 = 2, "Q2"
        Q3 = 3, "Q3"
        Q4 = 4, "Q4"

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="applications"
    )
    title = models.CharField(max_length=200)
    link = models.URLField()
    price = models.CharField(max_length=50, null=True, default=None)
    start_date = models.DateField(
        null=True, default=None, help_text="Format: YYYY-MM-DD"
    )
    quarter = models.PositiveSmallIntegerField(choices=Quarter.choices)
    justification = models.TextField(help_text="Why this course is important for you?")

src/engine/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    TemplateView,
    UpdateView,
)

from src.engine.models import Application


class ApplicationListView(LoginRequiredMixin, ListView):
    model = Application

    def get_queryset(self):
        return self.request.user.applications.all()


class ApplicationCreateView(LoginRequiredMixin, CreateView):
    model = Application
    fields = ["title", "link", "price", "start_date", "quarter", "justification"]
    success_url = reverse_lazy("engine:list")
    template_name_suffix = "_create_form"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        form.fields["price"].required = False
        form.fields["start_date"].required = False

        return form

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ApplicationUpdateView(LoginRequiredMixin, UpdateView):
    model = Application
    fields = ["title", "link", "price", "start_date", "quarter", "justification"]
    success_url = reverse_lazy("engine:list")
    template_name_suffix = "_update_form"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        form.fields["price"].required = False
        form.fields["start_date"].required = False

        return form


class ApplicationDeleteView(LoginRequiredMixin, DeleteView):
    model = Application
    success_url = reverse_lazy("engine:list")


class ChangeLanguageView(TemplateView):
    template_name = "engine/change_language.html"

src/content/templates/engine/application_confirm_delete.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

<h4>Delete the application</h4>

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete application "{{ object.title }}"?</p>
    {{ form }}
    <input class="btn btn-danger" type="submit" value="Confirm">
</form>

{% endblock %}

src/content/templates/engine/application_create_form.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

<h4>{% trans 'Create new application' %}</h4>

<form method="post">

    {% csrf_token %}
    {% bootstrap_form form %}

    <a class="btn btn-danger" href="{% url 'engine:list' %}"><i class="bi bi-x-lg"></i> Cancel</a>
    <button class="btn btn-success"><i class="bi bi-plus-lg"></i> Create</button>

</form>

{% endblock %}

src/content/templates/engine/application_list.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}
<h4>Your applications</h4>
{% if application_list %}
<table class="table">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Link</th>
        <th scope="col">Price</th>
        <th scope="col">Start date</th>
        <th scope="col">Quarter</th>
        <th scope="col">Justification</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for application in application_list %}
    <tr>
        <td>{{ application.pk }}</td>
        <td>{{ application.title }}</td>
        <td><a href={{ application.link }}>{{ application.link }}</a></td>
        <td>{{ application.price|default_if_none:"—" }}</td>
        <td>{{ application.start_date|default_if_none:"—" }}</td>
        <td>{{ application.quarter }}</td>
        <td>
            {% if application.justification|length <= 30 %}
            {{ application.justification }}
            {% else %}
            <details>
                <summary>Justification is too long. Click here to expand!</summary>
                <p>{{ application.justification }}</p>
            </details>
            {% endif %}

        </td>
        <td>
            <a class="btn btn-warning" href="{% url 'engine:update' application.pk %}">
                <i class="bi bi-pencil-square"></i> Update
            </a>
            <a class="btn btn-danger" href="{% url 'engine:delete' application.pk %}">
                <i class="bi bi-trash"></i> Delete
            </a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>You don't have any applications yet, consider creating one!</p>
{% endif %}
<p>
    <a href="{% url 'engine:create' %}">
        <button class="btn btn-success"><i class="bi bi-plus-lg"></i> Create a new application</button>
    </a>
</p>

{% endblock %}

src/content/templates/engine/application_update_form.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

<h4>{% trans 'Update the application' %}</h4>

<form method="post">

    {% csrf_token %}
    {% bootstrap_form form %}

    <a class="btn btn-danger" href="{% url 'engine:list' %}"><i class="bi bi-x-lg"></i> Cancel</a>
    <button class="btn btn-success"><i class="bi bi-check-lg"></i> Update</button>

</form>

{% endblock %}

src/content/templates/engine/change_language.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

{% get_current_language as language_code %}
{% get_available_languages as languages %}

<h4>{% trans 'Change language' %}</h4>

<form action="{% url 'set_language' %}" method="post">

    {% csrf_token %}

    <input name="next" type="hidden" value="{{ redirect_to }}"/>

    <div class="form-group">
        <label class="form-control-label" for="language-field">{% trans 'Select the language' %}</label>
        <select name="language" class="form-control" id="language-field">
            {% for code, name in languages %}
            <option value="{{ code }}" {% if code== language_code %} selected="selected" {% endif %}>
                {{ name }} ({{ code }})
            </option>
            {% endfor %}
        </select>
    </div>

    <button class="btn btn-success">{% trans 'Change' %}</button>

</form>

{% endblock %}